### ISSUE TITLE
Click symbols (IPA)

### ISSUE THREAD

**Issue by lvcivs** [psb1558/Elstob-font#1]
I am relaying a comment from Facebook relating to the web demo: https://psb1558.github.io/Elstob-font/ :

> Christopher Ray Miller: I notice that three click symbols (two between the voiced pharyngeal fricative symbol and the dotted O for a bilabial click; the other the rotated minuscule t preceding the stretched retroflex t symbol) are old symbols deprecated since the Kiel convention and replaced by || and ! and | (interdental) or superimposed = and | (alveolar). Small market segment, but those wanting standard IPA click symbols might forego this font for that purpose despite its other merits.

There is a relevant paragraph on Wikipedia in the section "Letter Forms", second paragraph: https://en.wikipedia.org/wiki/International_Phonetic_Alphabet#Letter_forms

https://en.wikipedia.org/wiki/Dental_click
https://en.wikipedia.org/wiki/Lateral_click
https://en.wikipedia.org/wiki/Alveolar_click

The concerned Unicode points are U+01C0 to U+01C2 (or U+01C3).

![Elstob_screenshot_clicks](https://user-images.githubusercontent.com/1976329/75392847-289b9600-58ed-11ea-9f4e-17ab0f79ba71.png)

**Comment by psb1558** [comment]
Thank you -- I will include the up-to-date click symbols.

**Comment by psb1558** [comment]
It's done now.
