### ISSUE TITLE
Wrong glyph for U+0281 LATIN LETTER SMALL CAPITAL INVERTED R

### ISSUE THREAD

**Issue by dscorbett** [psb1558/Elstob-font#10]
The glyph for U+0281 LATIN LETTER SMALL CAPITAL INVERTED R looks like a turned ⟨ʀ⟩ in version 1.005, but it should look like an upside-down ⟨ʀ⟩.

**Comment by psb1558** [comment]
Thanks! I have fixed it (fortunately the problem was only in the roman face) and will put up compiled fonts in a day or so.
