### ISSUE TITLE
Missing tag for‌ 1.006

### ISSUE THREAD

**Issue by alerque** [psb1558/Elstob-font#11]
I discovered this font because somebody that had forked it (@calligraffiti) stared my project [fontship](https://github.com/theleagueof/fontship). It looks **amazing**!

I'm not setting up Arch Linux packages for it. I noticed some commits that suggest 1.006 is the latest release, but the latest git tag is 1.003. Can you add tags for the points where the missing release(s) happened? That will make distro packaging a lot easier.

(Fontship isn't quite ready for this project yet, but when it is I might contribute some easier build tooling for you if your interested.)

**Comment by psb1558** [comment]
I've done a release, which should drop the v1.006 tag.

Fontship looks interesting! Elstob seems to be (again) headed for Google Fonts, so it kinda has to use their tools.

**Comment by alerque** [comment]
Thanks for the tag.

I don't think getting this ready for Google Fonts should preclude use of Fontship as part of the development workflow or to release the font here on Github. Much of the build machinery it uses is Google sponsored code anyway! There is a little bit of an open question whether Google will be able to use `fontship` themselves, but I expect we can work through that (see [fontship#35](https://github.com/theleagueof/fontship/issues/35)) even if it means I have to re-license it.

Since I'm working through defaults for some more basic cases and I see this font has a few advanced needs I'll wait to revisit this until it has a few more builds under it's belt, but since you can already customize the rules or add commands to be run at any stage of the pipeline it really shouldn't be that hard to support.
