### ISSUE TITLE
Providing variable font with desktop version

### ISSUE THREAD

**Issue by adunning** [psb1558/Elstob-font#16]
Would you mind providing both the variable and static versions of the font in the desktop download? The nomenclature is a little confusing, since the variable versions are preferable with modern software. This would also make packaging easier; systems such as Homebrew fonts only allow for download of a single archive file. The way in which [Source Sans](https://github.com/adobe-fonts/source-sans-pro) is released, for instance, is handy.

**Comment by psb1558** [comment]
I'll have a look at what Source Sans does.

I didn't know that Homebrew served fonts.

**Comment by adunning** [comment]
Thank you! Yes, ElstobD is there at <https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-elstobd.rb> (would like to include the variable version as well; cf. <https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-source-serif-pro.rb>).

**Comment by psb1558** [comment]
Thanks for pointing that out. Much happier to see it on Homebrew and in the Linux repositories that have picked it up than on those piratical commercial sites (which rarely update their copies).

**Comment by alerque** [comment]
Sadly the font ecosystem these days is heavily weighted towards either commercial subscription font services or a wild west of freeware and pirated downloads. Good open source projects that are actively maintained don't have nearly as much exposure even when reasonable venues do exist. I know there are a couple efforts out there aiming to change that (e.g. [Type.World](https://type.world/)) but for now distro package systems are one of the best. It shouldn't need to be individual font project's job to instruct people on where best to get FOSS fonts, but at this point I feel that's what needs to happen.

I suggest adding a prominent line to the project README in front of the download information that actively promotes the use of Homebrew fonts and any other package systems that have picked this up. One more is Arch Linux, for which I maintain [packages](https://aur.archlinux.org/pkgbase/elstob-font/) for [otf-elstob](https://aur.archlinux.org/packages/otf-elstob/), [ttf-elstob](https://aur.archlinux.org/packages/ttf-elstob/), [ttf-elstob-desktop](https://aur.archlinux.org/packages/ttf-elstob-desktop/), and [ttf-elstob-variable](https://aur.archlinux.org/packages/ttf-elstob-variable/).

**Comment by alerque** [comment]
Just for reference, a pretty good place to track Linux package distribution status is Repology. Here is the [fonts:estob](https://repology.org/project/fonts:elstob/versions) entry which tracks what distros have packages and what version they are currently at. Homebrew packages do show up here, but Homebrew Fonts to do not (yet).

**Comment by psb1558** [comment]
The release for v1.014 is all in a single zip file. I've included a README to help people figure out which version(s) to install. Right now the directory structure is flat, but I wonder if it should be
```
         |---ttf
variable |
         |---otf
desktop  |
```
since the Elstob*.ttf and Elstob*.otf fonts are intended mainly as fallbacks for the variable version (per Google Fonts rules). (Actually, I wonder why I've bothered with the *.otf fonts at all.)

**Comment by psb1558** [comment]
This is done now.
