### ISSUE TITLE
Adding versicle/response signs (U+2123/U+211F)

### ISSUE THREAD

**Issue by adunning** [psb1558/Elstob-font#17]
Would you consider adding the ℣ (versicle, U+2123) and ℟ (response, U+211F) signs, please?

I noticed that these are among the few omissions in glancing over some early type specimens, such as [this version of Garamond from the sixteenth century](https://www.dbnl.org/tekst/voet004gold01_01/voet004gold01_01_0030.php):

![images-003](https://user-images.githubusercontent.com/1084407/102993473-27d78e80-4515-11eb-9f65-ad988fc27b6a.png)

**Comment by psb1558** [comment]
Response masters, with capital R for comparison:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/16215767/103142584-67e47000-46d3-11eb-9bee-1e6c802a9566.png">
Masters are Regular, weight min,  opsz min, opsz max, weight max, grade max.

I don't already have glyphs in the font with this kind of stroke, so I had to design it. Not sure I'm satisfied yet. I've made it in small cap size because that is more in line with actual usage than the cap size that most fonts have. In keeping with my goal of keeping the size of this font down as much as possible, I'd rather not have variants of this glyph.

Versicle to come shortly.

**Comment by psb1558** [comment]
Btw, what is this?
<img width="38" alt="image" src="https://user-images.githubusercontent.com/16215767/103142643-7b440b00-46d4-11eb-9045-1d9fea830cea.png">

**Comment by psb1558** [comment]
Stroke wider at the top, narrower at the base.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/16215767/103142898-01168500-46da-11eb-9a08-03ae8b49fc02.png">

**Comment by psb1558** [comment]
And the versicle.
<img width="435" alt="image" src="https://user-images.githubusercontent.com/16215767/103144722-4cda2600-46fc-11eb-91bb-1f016cb09a1c.png">

**Comment by alerque** [comment]
The design looks pretty good, but 2 of these masters for both Glyphs seem to have different x-heights. Is that intentional? Since I don't know what axis each of these masters represent I'm not sure if this is right or wrong, but it seems suspect.

If I were to tweak the design I **might** fiddle with it to make the descenders for each of these roughly the same depth. Since they will frequently be used in context with each other it seems like it might benefit some page layouts if the vertical metrics for lines with each came out the same. I'm not actually sure this makes sense but it would be something to play with. The response sign in particular seems pretty deep.

**Comment by psb1558** [comment]
Thanks for the comment, @alerque ! The differing x-heights (or small-cap height, in this case) in the middle are for the optical size masters: as the optical size decreases, x-height and small-cap height both increase. (Normal is approximately in the middle, where the other masters are.)

For the depth of the stroke I was following the model @adunning provided, but I see that the redesign of these characters for [JuniusX](https://github.com/psb1558/Junicode-New/issues/36), and the models I used for that, had them at the same depth, so we'll try
<img width="132" alt="image" src="https://user-images.githubusercontent.com/16215767/103151883-20e89000-4750-11eb-931f-4d4c35790270.png">
I'm pretty happy with the tops of the strokes, but not yet with the bottoms, so will post another attempt later.

**Comment by psb1558** [comment]
Wider but chopped off at bottom.
<img width="132" alt="image" src="https://user-images.githubusercontent.com/16215767/103157597-7d64a300-4782-11eb-9097-36e9b3653839.png">

**Comment by alerque** [comment]
Oh that's looking shinny!

**Comment by psb1558** [comment]
Italic.
<img width="410" alt="image" src="https://user-images.githubusercontent.com/16215767/103163438-e58ba700-47cb-11eb-9c4f-6773e82b37d1.png">

**Comment by adunning** [comment]
These look wonderful – thank you! If you're feeling bold, I think the stroke could be even wider on the heavier variants and a hair thinner on the lightest. In manuscript it's usually written with the same nib width as the rest of the letter. But I have not studied the print conventions for boldface closely, and it might look ridiculous.

I've no idea whether these ever appeared in the Fell types – I assume you have access to the *John Fell, 1625–1686: bishop, printer & typefounder* exhibition catalogue and Morrison's *John Fell, the University Press and the "Fell" types*. If not, I can check once our libraries reopen (hopefully next week).

**Comment by psb1558** [comment]
Thanks, very much, Andrew! I'll fiddle with the strokes, comparing the models I've got. In this face, the bold is a high-contrast face with fairly thin thins. (But one big problem with bold type is that it's a very late concept—so no early models!) By this time the influence of MS usage seems fairly weak in comparison with earlier faces like Garamond.

Access is a problematic concept in the year 2020. We've got several important books concerning Fell and his types on the shelves in Special Collections, where they are currently completely inaccessible. I have access to fuzzy online copies of the early specimen booklets, like everyone, and I got hold of the big 1925 specimen folio, thank heaven, before the pandemic, but I don't see these signs there. I'm not liturgist enough to know if they were used in the Church of England liturgy: if so, I'd expect there to be something relevant among the Fell types.

But I think of Fell as a starting point for this font, not a model I have to stick to. So as soon as we decide that response and versicle look good, we'll be done!

**Comment by adunning** [comment]
That's what I figured. Happy to send you photographs if you need anything! Looks great to me!

**Comment by psb1558** [comment]
Here the thickness of the strokes is matched to that of the thin diagonals in letters like (small cap) V and X. For the Bold and Grade masters (the last two) the ends are thickened a bit more to increase contrast.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/16215767/103373700-a1d2bf00-4aa3-11eb-8b11-749d50fc73f4.png">
It's nice to be doing this the one week in the year when I have leisure to spend long periods meditating the best thickness, angle and curve of a single stroke.

**Comment by psb1558** [comment]
Bottom of the stroke for versicle looked light compared to that for response. Top of stroke also widened a smidge for Bold and Grade.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/16215767/103409743-22420000-4b36-11eb-9864-a0184a7c22cb.png">

**Comment by psb1558** [comment]
This is done, I think.

**Comment by adunning** [comment]
Thank you again for implementing these with such care!
