### ISSUE TITLE
Shape of ꝙ, U+A759

### ISSUE THREAD

**Issue by adunning** [psb1558/Elstob-font#18]
Arising from #17 – I think that the Garamond example shows ꝙ, U+A759, typically used for the 'quod' abbreviation:

![Garamond ꝙ](https://user-images.githubusercontent.com/1084407/103238222-ec3c2a80-4941-11eb-85aa-7a1925c7849d.png)

The normative version in MUFI is very similar:

![MUFI ꝙ](https://user-images.githubusercontent.com/1084407/103238362-68367280-4942-11eb-80f5-94f1e4123908.png)

The versions of this symbol in Brill and EB Garamond are variants on this design:

<img width="139" alt="Screenshot 2020-12-28 at 19 48 47" src="https://user-images.githubusercontent.com/1084407/103239539-b4cf7d00-4945-11eb-864e-7bb9044d6d9d.png">

<img width="140" alt="Screenshot 2020-12-28 at 19 49 12" src="https://user-images.githubusercontent.com/1084407/103239555-c31d9900-4945-11eb-89ed-f0e61548fb2a.png">

Elstob and Junicode by contrast give a simple diagonal stroke. I think the MUFI version is less ambiguous (compare the [relevant page of Cappelli](https://archive.org/details/lexiconabbreviat00capp/page/276/mode/2up)), and I've certainly seen it more frequently in print, but I am not sure if there is a history behind your version (possibly based on Cardo?).

**Comment by psb1558** [comment]
I'm not sure where my diagonal came from. Definitely not Cardo. Possibly Bischoff p. 160. For both Junicode/JuniusX and Elstob, I have generally tried to find some intersection of plain and generic, trying to omit features that might be seen as locale- or language-specific so as to come up wIth a shape that has a chance at being universally recognizable. I'm not sure what to do in this case.

I'm actually a bit confused as to why we have both U+A757 and U+A759, since I can't discern any semantic difference between them. Bischoff says pretty plainly that U+A757 = qui and U+A759 = quod, but the picture in Cappelli (6th ed.) is much messier, in addition to the strokes taking a variety of forms from simple horizontals and diagonals to an assortment of curves. As for the capital versions, I've omitted them from Elstob because I've never seen one in the wild, though I imagine they must come up occasionally.

**Comment by adunning** [comment]
I think things were more normalized in the later Middle Ages and in print. You can also see U+A757 in that Garamond specimen as ꝗᷓ (with combining U+1DD3) to make it 'quam'.

It's quite true that there is some fluidity between the characters, though Bischoff is simplifying on those pages to make it easier to identify versions of abbreviations from across periods (still, he is mostly using a long diagonal stroke coming above the baseline). If you're aiming to reproduce the characters as they were established in typography in the sixteenth and seventeenth centuries, I think the Unicode/MUFI models are the least ambiguous.

Here's [an example from 1526](http://bibliotecavirtual.larioja.org/bvrioja/i18n/catalogo_imagenes/grupo.do?path=89351&posicion=37&presentacion=pagina&registrardownload=0) showing both U+A757 and U+A759:

<img width="400" alt="Screenshot 2020-12-29 at 20 15 00" src="https://user-images.githubusercontent.com/1084407/103311540-8c618480-4a12-11eb-9155-fd4a88fdf4d8.png">

(Also note the ligated qꝫ, which I do not believe has made it into Unicode; MUFI PUA has it at E8BF.)

The capital versions show up the sixteenth century and earlier. [Here's U+A758 (with two different forms, or is that an artefact of casting/printing?) from the same book](http://bibliotecavirtual.larioja.org/bvrioja/i18n/catalogo_imagenes/grupo.do?path=89351&presentacion=pagina&posicion=12&registrardownload=0):

<img width="517" alt="Screenshot 2020-12-29 at 20 07 40" src="https://user-images.githubusercontent.com/1084407/103311156-83bc7e80-4a11-11eb-9bc4-4199147b66af.png">

But here is also evidence of flexibility, with this [example of U+A758 plus U+1DD3](http://bibliotecavirtual.larioja.org/bvrioja/i18n/catalogo_imagenes/grupo.do?path=89351&presentacion=pagina&posicion=7&registrardownload=0) ([here's another](http://bibliotecavirtual.larioja.org/bvrioja/i18n/catalogo_imagenes/grupo.do?path=89351&presentacion=pagina&registrardownload=0&posicion=100)), followed by using U+A757 as the equivalent lowercase:

<img width="291" alt="Screenshot 2020-12-29 at 19 04 03" src="https://user-images.githubusercontent.com/1084407/103307696-a0a08400-4a08-11eb-86bc-d88eb6644574.png">

Here's [yet another form of U+A759 from the nineteenth century](https://archive.org/details/piperollsociety24pipeuoft/page/94/mode/2up):

<img width="234" alt="Screenshot 2020-12-29 at 19 52 39" src="https://user-images.githubusercontent.com/1084407/103310397-6be3fb00-4a0f-11eb-935a-6200609ca039.png">

**Comment by psb1558** [comment]
It looks as if U+A759 wants a steeper diagonal at the very least. The version in the Garamond, with a curve attached to the stem of the q, steps beyond the bounds of legibility for me. I'm not sure a curve is necessary, but I'll experiment. I'm not after reproducing 17th c. practices, but rather offering a thing that's useful for the generality of medievalists. [For JuniusX I'll probably produce some variants of U+A759, as that font's idea is to welcome all such stuff. Elstob, on the other hand, wants to be small.]

I generally give in (with a sigh) on capitals. Even when they're not common, the case-matching often seems worth doing. I'm interested by the position of the diacritic in your image for U+A758 + U+1DD3 (and the other you link to). I have to choose a place for an anchor (where all diacritics will go). Should it be there? And do you have an example of U+A756?

Unicode no longer accepts ligatures, for the most part, their position being that ligatures should be produced by OpenType features (or the like). JuniusX has the MUFI/PUA code point, but also a q_et ligature via hlig, and I consider hlig the preferred way to do it. Elstob doesn't have MUFI/PUA code points, but I could include the ligature if it's likely to be generally useful. I'm interested by the way the bottom of the et sign crosses the stem of the q in your example. Is this common?

**Comment by psb1558** [comment]
An experiment.
<img width="164" alt="image" src="https://user-images.githubusercontent.com/16215767/103426708-66122500-4b89-11eb-8170-ec84b0b385df.png">

**Comment by psb1558** [comment]
Or probably more like
<img width="176" alt="image" src="https://user-images.githubusercontent.com/16215767/103426785-e59ff400-4b89-11eb-8cbb-43ded8e01f09.png">

**Comment by psb1558** [comment]
Masters (regular, weight min, opsz min, opsz max, weight max, grade max):
<img width="479" alt="image" src="https://user-images.githubusercontent.com/16215767/103432574-3d9d2180-4baf-11eb-8845-8f1338642d9c.png">
With U+1DD3:
<img width="94" alt="image" src="https://user-images.githubusercontent.com/16215767/103432582-6e7d5680-4baf-11eb-938d-723e05a0bcc2.png">

**Comment by psb1558** [comment]
Attempt at an uppercase version (U+A758).
<img width="296" alt="image" src="https://user-images.githubusercontent.com/16215767/103439672-09f0e480-4c0d-11eb-941c-a3810dccf3ea.png">
For now the top anchor is in the usual spot for a Q:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/16215767/103439723-5c320580-4c0d-11eb-8624-c2264a18e6fe.png">

**Comment by psb1558** [comment]
Italic. And the rule for this font is that where there's a case-pair there's got to be a small cap.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/16215767/103460219-8a354980-4ce2-11eb-9f19-cccc6361fb28.png">
Edit: the stroke for the small cap can't be just a scaled-down version of the stroke for the cap. It's got to match (approximately) the size of the lowercase stroke:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/16215767/103460719-9de2af00-4ce6-11eb-8244-5c3022ac7036.png">

**Comment by psb1558** [comment]
You can try these out in the variable version (fonts/variable). Not yet in static fonts or release.

**Comment by psb1558** [comment]
Changes are now in all versions available in the repository. New release (reorganized) wll come shortly.

**Comment by psb1558** [comment]
I have also revised the shapes of the Qq + stroke characters in [JuniusX](https://github.com/psb1558/Junicode-New).

**Comment by psb1558** [comment]
I think this is done now.
