### ISSUE TITLE
Possible enhancement (or substitute) for sups

### ISSUE THREAD

**Issue by Kybernator** [psb1558/Elstob-font#19]
Dear Professor Baker, thank you so much for your digitalization of the Fell types.

Presently, I am looking for the right font for the online part of a publication. I need to use small latin letters as footnote markers, and online, they will be accompanied by angular brackets (like [a], Wikipedia footnote style).
Normally, I would use OT feature _sups_ for those, but in Elstob, these only apply for the numbers.

- Would you consider adding small latin letters and brackets to the _sups_ feature?
- Otherwise, which of your optical sizes would you suggest to use for a _sups_-Substitute to accompany the Regular(12pt), rather the 10pt or the 8pt?

I am referring to the non-variable font for the moment, since I have no technical experience using variable fonts yet.

**Comment by psb1558** [comment]
I've deliberately kept Elstob fairly lean, so I'd be reluctant to add the whole alphabet in superscript. Two ideas:

1. [Junicode](https://github.com/psb1558/Junicode-font), which is my “everything” font, already has the whole alphabet in superscript. I could easily add the matching brackets. It is a big font for a web project, but I can help you subset it (if the project you're working on is free).

2. Alternatively, create a style or class in which Elstob is 60-70% of its standard size and raised by about 30%. Experiment with these numbers, and with medium and semibold weights to see which looks best (the footnote numbers should not look like black blobs on the page).

**Comment by Kybernator** [comment]
Thank you, I quite understand.
The project is indeed free, and if the final decision is for Junicode, I will gladly come back to your kind offer.

Meanwhile, I have found several kerning-issues in Elstob which might merit your attention. I have a sample-.pdf demonstrating them. 

What would be a way convenient for you to receive it?

**Comment by psb1558** [comment]
I'm working on a new release of Elstob, so your kerning issues PDF would be most welcome. Thanks very much!

**Comment by Kybernator** [comment]
Seen the address, please edit out, will send later this day.

**Comment by psb1558** [comment]
Thanks for the kerning doc. Superscript brackets are now in Junicode and will be included in the next build.
