### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by eclecticfluff** [psb1558/Elstob-font#20]
In the `Features and CharSet.pdf` file, a few things seem off.
For OpenType feature 18 (historical forms) the description doesn't seem to say much of anything.
> Changes s to s.

But considering the context my guess is that it's supposed to read like so:
> Changes s to ſ.

OpenType feature 27 feels like it's missing a comma:
> For lowercase d it offers a choice of ꝺ or ꝺ; the capital is changed to Ꝺ

as opposed to
> For lowercase d, it offers a choice of ꝺ or ꝺ; the capital is changed to Ꝺ

OpenType feature 29 has a strange period.
> Changes g/G to ᵹ/Ᵹ. and small cap ɢ to Ᵹ.

as opposed to
> Changes g/G to ᵹ/Ᵹ and small cap ɢ to Ᵹ.

(features 31--33 have the same issue. At the very least, all cases of and like this in the list should be consistent.

Feature 37 doesn't actually provide any textual example of what the setting does.

I think these are all the typos in the documentation, but if I find more I'll add them.

**Comment by psb1558** [comment]
Thankis for these. I'm going to be moving the documentation over to LuaTeX; when I do I'll make these corrections.
