### ISSUE TITLE
Width of U+202F (NARROW NO-BREAK SPACE)

### ISSUE THREAD

**Issue by Alice196498** [psb1558/Elstob-font#24]
The width of U+202F in this typeface is much larger than the common ſpace and no-break ſpace, when it ſhould be equal in width to U+2009 THIN SPACE. This ſpace is traditionally defined as ⅕ of an em,—that is, one-fifth of the body of the type,—which is here 1000 units ; thus, both U+2009 and U+202F would be 200 units wide : however, given that the common ſpace is only 189 units wide, this is problematick. One potential ſolution would be to apply the rule of letting it be about 70% of the common ſpace’s width, which would make both 132 units wide.
 A much better ſolution, in my opinion, would be to reſize the common ſpace to be equal to that of the 3-em-ſpace, which is 333 units wide, and let both the narrow no-break ſpace and thin ſpace be equal to 200 units. My reaſoning is thus : in traditional typeſetting, the 3-em ſpace is uſed as the [ſtandard ſpace between words,](https://books.google.com/books?id=Wk0uAQAAIAAJ&pg=PA83#v=onepage&q&f=false) and was alſo called the thick ſpace, or “[ compoſing ſpace](https://books.google.com/books?id=p61fAAAAcAAJ&pg=PA5#v=onepage&q&f=false).”
 In traditional printing in Engliſh, as well as in French, German, and other languages, the narrow no-break ſpace is greatly uſed for punctuation and abbreviations ; therefore, it is of great importance for many uſers that it have the proper width.

**Comment by psb1558** [comment]
Thanks for  pointing out the problem with U+202F. I tried the wider width for U+0020, and I don't think I can go there. Indeed, quickly surveying some of the fonts I respect most, I can't find any where U+0020 is 1/3 of an em (and I strongly doubt that that is the width of the space in the Chicago manual of style). I'm going to survey a wider selection of fonts and make adjustments.

**Comment by Alice196498** [comment]
I’m glad I could point out ſomething helpful ! Moſt typefaces as of late like to make the ſpaces very, very thin—I’m not ſure why, but I amn’t a great fan of the habit. In the days of hand-ſet type, as thoſe books I linked did, and all older books as well, the thick ſpace was the ſtandard ſpace uſed and recommended, but they’d uſually end up with uſing either wider or occaſionally ſhorter ſpacing between words to either drive out a word, get in a word, or otherwiſe allow the lines to be properly juſtified. If you look at the examples in the Manual of Style, you can ſee anywhere that it’s ragged, the ſpacing is generally rather wide, but tends to be either a 3-em ſpace, or a little wider if the line before is alſo wide, becauſe ſpacing evenly is the goal. Given that this is a rather traditional typeface, I’d highly recommend following the traditional ſtandard, but underſtand if you, as a type deſigner, would chuſe to do what is moſt pleaſing to your eye and ſenſibilities. Trying it out for myſelf, though, I think it depends on how much text is being diſplayed, and at what ſize whether a 3-em ſpace is good, or a ſlightly ſmaller one is. It can be difficult to find a balance between the proſcribed methods and appearances, which is one reaſon that it’s both an art and a ſcience.

**Comment by psb1558** [comment]
Experimentally, I've added a custom Spacing (SPAC) axis running 0-1, with 189 font units on one end (190 in the italic) and 333 on the other end. Default is 0. Look for the files `Elstob-with-spacing.ttf` and `Elstob-Italic-with-spacing.ttf` in fonts/variable. The axis affects whitespace characters that aren't pegged explicitly to the em-square: space, non-breaking space, thin space, narrow non-breaking space.
One can easily generate static instances with revised spacing by editing the number in line 14 of `fix-spacing.xsl` (use any number between 0 and 1, e.g. 0.45) before running the build script.
Let me know what you think.

**Comment by Alice196498** [comment]
That’s a very elegant and creative ſolution ! I’ve juſt been teſting it with the pre-built verſion (as I am unſure of how to build it with on my Linux ſyſtem), and it works quite well in applications that ſupport toggling the feature.
 This ſeems to have ameliorated both the title iſſue, and extra ſpacing concerns I had—thank you ſo very much for working with me in order to come to a ſolution that can ſatisfy everyone.

I ſhall note that the ſpecimen page doeſn’t like the ſpacing ſlider, but this doeſn’t ſeem to be a problem with the typeface ; rather, it appears to be a problem with the way the ſpecimen page applies its ſettings.

**Comment by psb1558** [comment]
Not a lot of apps supporting variable fonts on Linux, as far as I know. But if you are a TeX user LuaTeX supports them very well as of the very latest version of luaotfload, which is included in the TeXLive release from this spring. The current version of the Elstob Manual is built with LuaTeX, and the file ElstobManual.sty shows one way to do it.

Of course the most widely used browsers work with variable fonts, on Linux and elsewhere.

Elstob should be easy to build on Linux, since the tools are Python. I'll add a how-to to the README.

**Comment by Alice196498** [comment]
This has become my favourite typeface, and I’m uſing it for the UI on my devices, and the main typeface on Web pages that uſe the Latin alphabet—at leaſt, if there’s ſupport for the characters. So far, Vietnameſe and Sámi are the main Latin-baſed languages outſide of African and Indigenous U. S. languages that are lacking ſupport which I’ve come acroſs—ſupporting thoſe would, in my opinion, make this one of, if not the, moſt verſatile typefaces for Latin-baſed languages, and would potentially be rather helpful for ſpeakers of thoſe languages, eſpecially in places like Africa.
 It being a variable typeface with optical ſizing is one big reaſon for my uſing it ſo extenſively, but another is becauſe it’s nearly perfectly ſuited to my needs and ſenſibilities. This does let me more readily find bugs or potential problems. I don’t uſe TeX or LuaTeX myſelf, as if I need to typeſet ſomething myſelf, I’ll uſe InDeſign in a VM.
 I’ll be looking forward to the build documentation. I’ve been uſing a copy of FontLab to teſt and build from the compiled verſions, which could, I ſuppoſe, introduce ſome kind of iſſue ſomewhere.

**Comment by psb1558** [comment]
Thanks for the kind words. I limited the language coverage in the beginning to keep the project manageable, but now there seems little reason not to add more coverage.

I would not have guessed that InDesign could run in a VM.

I have no idea whether editing the compiled version of Elstob with FontLab would cause problems. I doubt it, and if you're trying out a new or revised feature (as in the contextual long s thread), it may be the easiest thing. And if it continues to work in InDesign (which is pretty persnickety about variable fonts), then all is well.

**Comment by Alice196498** [comment]
If you’re conſidering adding more language coverage, I could try to compile the moſt potentially beneficial glyphs in a ſeparate iſſue thread for eaſier tracking. There’s already one for Vietnameſe, and its glyphs would help a few other languages.
 InDeſign does run in a VM. It doeſn’t have the beſt performance ever, but it works well enough to not be a problem.
 Editing it with FontLab _ſeems_ to uſually work okay. I had a couple of times where things got rather upſet, and I amn’t ſure why that was, but redid my teſting verſion and it ſeems to have decided to be agreeable. So it appears that that method iſn’t awful—it works well for making quick reviſions or teſts of ideas, or trying to figure out why ſomething iſn’t doing what I’d expect.

**Comment by psb1558** [comment]
Issues for additional language coverage would be very helpful. As this one seems to be resolved now, I'll close this now.
