### ISSUE TITLE
calt affecting longs_l and longs_longs_l ligatures

### ISSUE THREAD

**Issue by Alice196498** [psb1558/Elstob-font#25]
The new calt, which ſeems to replace longs by longs.alt2 before certain glyphs ſeems to break the ligatures for ſl and ſſl, but ſtrangely not ſi or ſſi, or any others I’ve noticed ſo far. Removing the l in the calt claſs fixes it, but whether that breaks anything elſe, I am unſure. Is this l meant to be lslash ? Aſſuming ſo, and replacing l with lslash fixes that, and puts longs.alt2 before ł, but the two ſtill collide ; thus the kerning of thoſe two (and longs or longs.alt2 thorn if no ligature be made) might need to be adjuſted.

**Comment by psb1558** [comment]
longs is replaced by longs.alt2 before l in case `liga` is off; but then there should be other liga rules to take account of the sequence longs.alt2 l, and I seem to have overlooked those. I'll fix and post new versions in the next day or two.

I recently switched to a new kerning system, and it will take a while to get the kinks worked out.

**Comment by Alice196498** [comment]
Oh, all righ—good to know. That’s a good idea, as ſome things have `liga` off for ſome reaſon. I do notice that the kerning ſeems to be a bit more even now in general—if there’s anything I can to to help, I’d be glad to lend a hand.

**Comment by psb1558** [comment]
What you can do to help is raise an issue if you spot a bad kerning pair.

**Comment by psb1558** [comment]
This is fixed, and the version with the new axis is now standard, so grab it in fonts/variable. I'm closing this one now.
