### ISSUE TITLE
Turkiſh ğ miſſing from the Italick face.

### ISSUE THREAD

**Issue by Alice196498** [psb1558/Elstob-font#28]
I was reading, and noticed that ğ is preſent in the Roman face, but ſeems to be miſſing from Italick. Romanian Ș and ș as well as Ț and ț are alſo miſſing from Italick.

**Comment by psb1558** [comment]
Thanks for pointing this out. It is fixed now. These characters (lc, uc, sc) will be in the italic next time I build the font.
