### ISSUE TITLE
“Croſsbar” renders wiþ ſſb ligature by default wiþ contextual Long S.

### ISSUE THREAD

**Issue by 23moirai32** [psb1558/Elstob-font#29]
I’m pretty ſure þe ſtandard form for þis word in Engliſh is wiþ a ſhort s in between þe ſ & b.  (Croſs-bar, but wiþout þe hyphen.) :D

**Comment by Alice196498** [comment]
It’s true. With SS08, contextual long s, when the language is ſpecified as Engliſh, what ſhould be rendered ſs‌b is inſtead rendered as ſſb. In the default/non ſpecified language ſet, ſſb is correct. The other defined languages do print correctly in this caſe ; thus, it’s an overſight in the Engliſh rule definitions.

**Comment by psb1558** [comment]
Oddly, I've got a rule for this, but I commented it out. I'll fix and test.

**Comment by psb1558** [comment]
This is fixed now, and it will be in the next build I post (2.000beta5), probably within the next couple of days.
