### ISSUE TITLE
Below-base diacritic blocks tittle removal

### ISSUE THREAD

**Issue by dscorbett** [psb1558/Elstob-font#3]
The tittle of ⟨i⟩ or ⟨j⟩ is not removed before an above-base diacritic when there is also a below-base diacritic. For example, here is ⟨ị̊j̣̊į̊⟩.
![ị̊j̣̊į̊](https://user-images.githubusercontent.com/1124347/78595603-49260c80-7818-11ea-8aea-ed3a292a2493.png)

**Comment by psb1558** [comment]
The above diacritic should come before the below diacritic. This is also the behavior of Brill (great academically oriented font which I have often used as a guide for the correct behavior of features):
<img width="454" alt="image" src="https://user-images.githubusercontent.com/16215767/78597740-1251f580-781c-11ea-9515-03fd9857c1e5.png">

**Comment by dscorbett** [comment]
Both orders are canonically equivalent. NFC puts the below-base diacritic first, so this won’t work in any renderer that applies Unicode normalization, like most web browsers.

**Comment by psb1558** [comment]
Okay, I see what you mean. Harfbuzz does a lot of normalization, and it's widely used. I'll have to add another rule to take account of this.

**Comment by psb1558** [comment]
Fortunately the fix is not complicated. Here are the sequences in Firefox:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/16215767/78602994-5b5a7780-7825-11ea-83b9-cea058318519.png">
I will apply the same fix in italic, do some testing, and post when satisfied.

**Comment by psb1558** [comment]
And italic.
<img width="145" alt="image" src="https://user-images.githubusercontent.com/16215767/78609497-ccebf300-7830-11ea-805e-69e7e38a1a51.png">
Next is testing.

**Comment by psb1558** [comment]
Fonts in the fonts directory are now fixed (but no release yet). I'll leave this issue open for a few days, in case there are problems with the fix.

**Comment by dscorbett** [comment]
The fix looks good to me.

**Comment by psb1558** [comment]
The fix is now in release 1.002.
