### ISSUE TITLE
The kerning of numbers around dashes is uneven

### ISSUE THREAD

**Issue by lunarythia** [psb1558/Elstob-font#32]
![image](https://github.com/psb1558/Elstob-font/assets/63614345/f6bd16ed-ab0e-4bfc-a9d3-4812da885fcf)

![image](https://github.com/psb1558/Elstob-font/assets/63614345/972d562d-943e-45bb-936c-b420f87f0cd6)

The kerning of numbers around dashes is uneven. Some numbers should have more whitespace to look more even.

**Comment by psb1558** [comment]
Surveying various fonts, it seems one does not kern non-proportional figures, even though the output can be awkward. I have kerning for proportional figures, but it could be improved. I'll work on this.

**Comment by psb1558** [comment]
I believe that fixed-width figures are not kerned so as to keep them fixed-width (e.g. they can be arranged in neat columns). However, the proportional numbers in the latest release, version 2.100, are kerned against hyphens and dashes.

I'm closing this now as finished.
