### ISSUE TITLE
Weirdness with combining above diacritics when there are diacritics below

### ISSUE THREAD

**Issue by lunarythia** [psb1558/Elstob-font#36]
![圖片](https://github.com/psb1558/Elstob-font/assets/63614345/be67eb49-c257-4bc8-aa49-e0be53ccfde2)

In the second row, ị́, ị̀, ị̂, ị̈, and ị̃ all have an extraneous tittle (ị is fine though). In the third row, for some reason ḭ has no tittle, even though it probably should.

```latex
\documentclass[14pt]{article}
\usepackage{fontspec}
\setmainfont[BoldFont=*,
BoldFeatures={RawFeature={axis={wght=700}}},
ItalicFont=*-Italic,
BoldItalicFont=*-Italic,]{Elstob}
\begin{document}
\noindent i í ì î ï ĩ\\
ị ị́ ị̀ ị̂ ị̈ ị̃ << Every character except for the first has an extra tittle\\
ḭ ḭ́ ḭ̀ ḭ̂ ḭ̈ ḭ̃ << First character in this row lacks a tittle\\
į į́ į̀ į̂ į̈ į̃ << (no problems)\\
\end{document}
```

**See related issue over at Junicode:** psb1558/Junicode-font#238

**Comment by psb1558** [comment]
In the matching [Junicode issue](https://github.com/psb1558/Junicode-font/issues/238) it is explained that, for unusual combinations of combining marks, one sometimes has to place U+034F COMBINING GRAPHEME JOINER between the base character and the first mark. Some revisions to the Elstob feature code were needed to make this work consistently: the revisions are in version 2.101, just now released.
