### ISSUE TITLE
Downloading project not working properly

### ISSUE THREAD

**Issue by Chirotheques** [psb1558/Elstob-font#39]
When downloading the project, the font files are missing.

**Comment by psb1558** [comment]
I was thinking, why download the fonts with the source when you can get them in the release archive? I can change that, but no one has ever complained about it before.

**Comment by Chirotheques** [comment]
Sorry for the very late reply. If you don't mind, please do change it, or at least mention somewhere that they are not available when downloading the source. Thank you very much, and once again, very sorry for the late reply.

**Comment by psb1558** [comment]
Okay, I've revised the "ignore" attributes, so fonts should now download with the source.

**Comment by alerque** [comment]
This is a step backwards. The repo size will inflate quickly with storing binary blobs that are *properly* generated artifacts. Attaching them to releases was better, and if intermediate non-release versions are desirable a CI pipeline that posts them as build artifacts for each commit run would be in order.

I know a lot of font projects *do* stuff the generated font binaries in VCS and even do so frequently, but in spite of Google liking this workflow it is not a good one. In my relatively informed opinion of course.

**Comment by psb1558** [comment]
@alerque: I'm not sure I understand. Are you suggesting that I shouldn't have binaries in the repo? Because they're kind of a pain, and I wouldn't mind getting rid of them.

I haven't looked into CI yet, unfortunately. Very lazy when it comes to learning new stuff.

**Comment by alerque** [comment]
Yes, not having binaries in the repo is exactly what I'm suggesting.

**Comment by psb1558** [comment]
A year and more later, I'll close this with a note that there are no longer fonts in the repo.
