### ISSUE TITLE
U+02F7, low tilde

### ISSUE THREAD

**Issue by adunning** [psb1558/Elstob-font#4]
The ˷ (U+02F7) character is a useful for transcribing certain types of medieval punctuation, and I assume that it also has other functions, as it appears in several different scholarly fonts (see for example [the list of characters in the Brill font](https://brill.com/page/BrillFontDownloads/Download-The-Brill-Typeface)). Would it be possible for Elstob to include this, please?

**Comment by psb1558** [comment]
Added. It will be in the next build (probably tomorrow).

**Comment by psb1558** [comment]
Finished fonts now in the "fonts" folder.

**Comment by adunning** [comment]
Thank you!
