### ISSUE TITLE
Italic font: ccmp is a bit too trigger-happy

### ISSUE THREAD

**Issue by drs-p** [psb1558/Elstob-font#40]
I found that the ccmp feature in the italic font is a bit too trigger-happy, at least with Latex (both Lualatex and Xelatex); it replaces i and j with their dotless versions whenever they are followed by an accented character. An example:
```
\documentclass[varwidth, border=2pt]{standalone}
\usepackage{fontspec}
\newcommand*{\test}{io i\~{o} ja j\'{a}}
\begin{document}
\fontspec{Elstob-Italic.ttf} \test\space (default) \\
\fontspec{Elstob-Italic.ttf}[RawFeature = {-ccmp}] \test\space (without ccmp)
\end{document}

```
This results in:
![bug](https://github.com/psb1558/Elstob-font/assets/102804722/2ee59de9-f2d2-481d-baa5-1901df38890c)

The roman version works correctly (or at least the way I expect it to :-) ).

**Comment by psb1558** [comment]
Stupid mistake. I have fixed it, and will try to get a new release out sometime in the next few days.
