### ISSUE TITLE
f.alt and liga in italic

### ISSUE THREAD

**Issue by xm-casanova** [psb1558/Elstob-font#6]
When the `calt` feature is activated (e.g. LibreOffice), some ligatures (`ffi`, `ffl`, `fi`, `fl`) don't work for the italic fonts. Is it possible to add lines like these in the `liga` feature? Many thanks.

    sub f f.alt i by uniFB03;
    sub f f.alt l by uniFB04;
    sub f.alt i by uniFB01;
    sub f.alt l by uniFB02;

**Comment by psb1558** [comment]
These rules are in the roman face and should have been in the italic. I'll fix it shortly.

**Comment by psb1558** [comment]
Done now.
